### ISSUE TITLE
enable zipfile loading for all functions

### ISSUE THREAD

**Issue by bluegenes** [sourmash-bio/pyo3_branchwater#108]
Enable `zip` loading for all functions:

- [x] #58 introduced reading zipfiles for mastiff indexing (loading pathlists from zip)
- [x] #105 more zip utils (load sketches, standardized reporting) & added zip load for `index`, `multisearch`
- [x] #99  zip loading for `manysearch`
- [x] #106 zip loading for `fastmultigather`
- [x] #112 zip loading for `fastgather`
